/**
 * English stopwords for keyword extraction.
 * Curated from NLTK + spaCy + resume-domain common words.
 * Kept inline (no runtime deps) and small.
 */
export const STOPWORDS: ReadonlySet<string> = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'by', 'for', 'from', 'has',
  'have', 'in', 'is', 'it', 'its', 'of', 'on', 'or', 'that', 'the', 'to',
  'was', 'were', 'will', 'with', 'this', 'these', 'those', 'you', 'your',
  'we', 'our', 'us', 'they', 'their', 'them', 'i', 'me', 'my', 'he', 'she',
  'his', 'her', 'but', 'if', 'not', 'so', 'do', 'does', 'did', 'can',
  'could', 'would', 'should', 'may', 'might', 'must', 'shall', 'about',
  'all', 'any', 'each', 'few', 'more', 'most', 'other', 'some', 'such',
  'than', 'too', 'very', 'just', 'also', 'into', 'over', 'after', 'before',
  'between', 'under', 'again', 'further', 'then', 'once', 'here', 'there',
  'when', 'where', 'why', 'how', 'both', 'through', 'during', 'above',
  'below', 'up', 'down', 'out', 'off', 'no', 'yes', 'only', 'own', 'same',
  'being', 'having', 'doing', 'while', 'against', 'until', 'because',
  'without', 'within', 'along', 'across', 'behind', 'beyond', 'despite',
  'except', 'like', 'near', 'since', 'unless', 'whether', 'able', 'get',
  'got', 'gets', 'getting', 'make', 'makes', 'made', 'making', 'take',
  'takes', 'taken', 'taking', 'come', 'comes', 'came', 'coming', 'go',
  'goes', 'went', 'going', 'see', 'sees', 'saw', 'seen', 'seeing',
  'know', 'knows', 'knew', 'known', 'knowing', 'think', 'thinks', 'thought',
  'want', 'wants', 'wanted', 'wanting', 'need', 'needs', 'needed', 'needing',
  'use', 'uses', 'used', 'using', 'find', 'finds', 'found', 'finding',
  'give', 'gives', 'gave', 'given', 'giving', 'tell', 'tells', 'told',
  'tell', 'telling', 'work', 'works', 'worked', 'working', 'call', 'calls',
  'called', 'calling', 'try', 'tries', 'tried', 'trying', 'ask', 'asks',
  'asked', 'asking', 'feel', 'feels', 'felt', 'feeling', 'leave', 'leaves',
  'left', 'leaving', 'put', 'puts', 'putting', 'mean', 'means', 'meant',
  'meaning', 'keep', 'keeps', 'kept', 'keeping', 'let', 'lets', 'letting',
  'begin', 'begins', 'began', 'beginning', 'help', 'helps', 'helped',
  'helping', 'talk', 'talks', 'talked', 'talking', 'turn', 'turns', 'turned',
  'turning', 'start', 'starts', 'started', 'starting', 'show', 'shows',
  'showed', 'shown', 'showing', 'hear', 'hears', 'heard', 'hearing',
  'play', 'plays', 'played', 'playing', 'run', 'runs', 'ran', 'running',
  'move', 'moves', 'moved', 'moving', 'live', 'lives', 'lived', 'living',
  'believe', 'believes', 'believed', 'believing', 'bring', 'brings',
  'brought', 'bringing', 'happen', 'happens', 'happened', 'happening',
  'write', 'writes', 'wrote', 'written', 'writing', 'provide', 'provides',
  'provided', 'providing', 'sit', 'sits', 'sat', 'sitting', 'stand',
  'stands', 'stood', 'standing', 'lose', 'loses', 'lost', 'losing',
  'pay', 'pays', 'paid', 'paying', 'meet', 'meets', 'met', 'meeting',
  'include', 'includes', 'included', 'including', 'continue', 'continues',
  'continued', 'continuing', 'set', 'sets', 'setting', 'learn', 'learns',
  'learned', 'learning', 'change', 'changes', 'changed', 'changing',
  'lead', 'leads', 'led', 'leading', 'understand', 'understands',
  'understood', 'understanding', 'watch', 'watches', 'watched', 'watching',
  'follow', 'follows', 'followed', 'following', 'stop', 'stops', 'stopped',
  'stopping', 'create', 'creates', 'created', 'creating', 'speak',
  'speaks', 'spoke', 'spoken', 'speaking', 'read', 'reads', 'reading',
  'allow', 'allows', 'allowed', 'allowing', 'add', 'adds', 'added',
  'adding', 'spend', 'spends', 'spent', 'spending', 'grow', 'grows',
  'grew', 'grown', 'growing', 'open', 'opens', 'opened', 'opening',
  'walk', 'walks', 'walked', 'walking', 'win', 'wins', 'won', 'winning',
  'offer', 'offers', 'offered', 'offering', 'remember', 'remembers',
  'remembered', 'remembering', 'consider', 'considers', 'considered',
  'considering', 'appear', 'appears', 'appeared', 'appearing', 'buy',
  'buys', 'bought', 'buying', 'serve', 'serves', 'served', 'serving',
  'die', 'dies', 'died', 'dying', 'send', 'sends', 'sent', 'sending',
  'expect', 'expects', 'expected', 'expecting', 'build', 'builds',
  'built', 'building', 'stay', 'stays', 'stayed', 'staying', 'fall',
  'falls', 'fell', 'fallen', 'falling', 'cut', 'cuts', 'cutting',
  'reach', 'reaches', 'reached', 'reaching', 'kill', 'kills', 'killed',
  'killing', 'remain', 'remains', 'remained', 'remaining', 'suggest',
  'suggests', 'suggested', 'suggesting', 'raise', 'raises', 'raised',
  'raising', 'pass', 'passes', 'passed', 'passing', 'sell', 'sells',
  'sold', 'selling', 'require', 'requires', 'required', 'requiring',
  'decide', 'decides', 'decided', 'deciding', 'pull', 'pulls', 'pulled',
  'pulling',
]);
